*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: /DLWUPEX/V_VAR_A................................*
TABLES: /DLWUPEX/V_VAR_A, */DLWUPEX/V_VAR_A. "view work areas
CONTROLS: TCTRL_/DLWUPEX/V_VAR_A
TYPE TABLEVIEW USING SCREEN '9008'.
DATA: BEGIN OF STATUS_/DLWUPEX/V_VAR_A. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/DLWUPEX/V_VAR_A.
* Table for entries selected to show on screen
DATA: BEGIN OF /DLWUPEX/V_VAR_A_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_A_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /DLWUPEX/V_VAR_A_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_A_TOTAL.

*...processing: /DLWUPEX/V_VAR_H................................*
TABLES: /DLWUPEX/V_VAR_H, */DLWUPEX/V_VAR_H. "view work areas
CONTROLS: TCTRL_/DLWUPEX/V_VAR_H
TYPE TABLEVIEW USING SCREEN '9000'.
DATA: BEGIN OF STATUS_/DLWUPEX/V_VAR_H. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/DLWUPEX/V_VAR_H.
* Table for entries selected to show on screen
DATA: BEGIN OF /DLWUPEX/V_VAR_H_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_H.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_H_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /DLWUPEX/V_VAR_H_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_H.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_H_TOTAL.

*...processing: /DLWUPEX/V_VAR_I................................*
TABLES: /DLWUPEX/V_VAR_I, */DLWUPEX/V_VAR_I. "view work areas
CONTROLS: TCTRL_/DLWUPEX/V_VAR_I
TYPE TABLEVIEW USING SCREEN '9002'.
DATA: BEGIN OF STATUS_/DLWUPEX/V_VAR_I. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/DLWUPEX/V_VAR_I.
* Table for entries selected to show on screen
DATA: BEGIN OF /DLWUPEX/V_VAR_I_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_I.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_I_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /DLWUPEX/V_VAR_I_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_I.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_I_TOTAL.

*...processing: /DLWUPEX/V_VAR_P................................*
TABLES: /DLWUPEX/V_VAR_P, */DLWUPEX/V_VAR_P. "view work areas
CONTROLS: TCTRL_/DLWUPEX/V_VAR_P
TYPE TABLEVIEW USING SCREEN '9004'.
DATA: BEGIN OF STATUS_/DLWUPEX/V_VAR_P. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/DLWUPEX/V_VAR_P.
* Table for entries selected to show on screen
DATA: BEGIN OF /DLWUPEX/V_VAR_P_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_P.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_P_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /DLWUPEX/V_VAR_P_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_P.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_P_TOTAL.

*...processing: /DLWUPEX/V_VAR_T................................*
TABLES: /DLWUPEX/V_VAR_T, */DLWUPEX/V_VAR_T. "view work areas
CONTROLS: TCTRL_/DLWUPEX/V_VAR_T
TYPE TABLEVIEW USING SCREEN '9006'.
DATA: BEGIN OF STATUS_/DLWUPEX/V_VAR_T. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/DLWUPEX/V_VAR_T.
* Table for entries selected to show on screen
DATA: BEGIN OF /DLWUPEX/V_VAR_T_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_T.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_T_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /DLWUPEX/V_VAR_T_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /DLWUPEX/V_VAR_T.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /DLWUPEX/V_VAR_T_TOTAL.

*.........table declarations:.................................*
TABLES: /DLWUPEX/TVAR_AU               .
TABLES: /DLWUPEX/TVAR_H                .
TABLES: /DLWUPEX/TVAR_IN               .
TABLES: /DLWUPEX/TVAR_P                .
TABLES: /DLWUPEX/TVAR_TX               .
